### ISSUE TITLE
To Do list for Initial Release:

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/Heptagram#182]
## Ticket Marked as Locked and Staff Only. Please reference sub-issues to take something on. @psyonix-engg is the lead on this issue, and you can direct any questions to them.
_This is basically a clearer version of [issue #103](https://github.com/Heptagram-Bot/Heptagram/issues/103)_

- [ ] make variable prefix, admin role id, etc, configurable per guild.
- [ ] make variable _admin_ role id configurable per guild. (see config.json file if confused) (make sure new roles match roles on commands)
- [ ]  make variable _user_ role id configurable per guild. (see config.json file if confused) (make sure new roles match roles on commands)
- [ ] make variable _muted_ role id configurable per guild. (see config.json file if confused)(make sure new roles match roles on commands)
- [ ] make owner ids a static defined thing for **ALL** of bot (make sure new roles match roles on commands)
- [ ] create **1 time** setup command. creates new guild "profile" that includes the user, admin, and muted role ids, and prefix they want to use. (creates roles or user can specify them) (see issue #103 if confused about "profiles") (issue #112)
- [ ] Tackle current known bugs (issues number #162, and more added as needed)
- [ ] Create unlock command (#102)
- [ ] Make warn system (#86) (@psyonix-engg I believe you may have already done this)
- [ ] Propper bot logging. Bot logging needs a good system. (#23)
- [ ] Fix help command. Embed maybe? Just make it look and feel better. Want admin commands to only be displayed if user who requests is an admin. (#22)

That’s It! When this list is done we will be ready for v1 release!
